import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/Main'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kenneth | Junior Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <Main/>
      <About />

      {/* <Image src='../public/assets/svg/ppperspective.png' className="" /> */}

      {/* <div className="w-1/2 h-1/2 m-24 rounded-xl backdrop-blur-lg bg-stone-50/25" ></div> */}

      
    </div>
  )
}
